#!/usr/bin/env bash
# restart nginx runnig as user nginx on port 8080
sudo pkill -f apache2
sleep 4
chmod 700 /etc/nginx/nginx.conf
sed -i ' s /80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
