#!/usr/bin/env bash
# restart nginx runnig as user nginx on port 8080
sudo pkill apache2
sleep 2
sudo chmod ugo+rw /etc/nginx/nginx.conf
sed -i -E 's/(listen.*)80 /\18080 /g' /etc/nginx/sites-enable/default
sudo -u nginx service nginx start
